services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=todo_list'
      - 'MARIADB_PASSWORD=todo'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=todo'
    ports:
      - '33006:3306'
    volumes:
      - 'mariadb_data:/var/lib/mysql'
volumes:
  mariadb_data:
    driver: local