spring:
  profiles:
    active: local
  config:
    import: optional:file:../../.env[.properties]

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:${db}
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
    level:
      root: info
      org.springframework.web: debug


